import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "ismail",
      email: "ismail@gmail.com",
      password: bcrypt.hashSync("teste"),
      isAdmin: true,
      isConducteur: false,
    },
    {
      name: "nouha",
      email: "nouha@gmail.com",
      password: bcrypt.hashSync("teste"),
      isAdmin: false,
      isConducteur: false,
    },
  ],
  employees: [
    {
      fullName: "John Doe",
      image: "/images/employe.jpg",
      cin: "A123456",
      email: "johndoe@example.com",
      phoneNumber: "+1 123-456-7890",
      type: "Full-time",
      salary: 5000,
    },
  ],

  products: [
    {
      name: "Red Bricks",
      slug: "red-bricks",
      category: "Bricks",
      image: "/images/bricks.jpg",
      price: 50,
      countInStock: 50,
      brand: "Amal Plancher Bricks",
      rating: 0,
      numReviews: 0,
      description:
        "High-quality red bricks for construction purposes. These bricks are durable and provide excellent strength for your building projects.",
      type: "",
      material: "Clay",
      reviews: [],
    },
    {
      name: "Ciment 35",
      slug: "ciment-35",
      category: "Ciment",
      image: "/images/cement.jpg",
      price: 400,
      countInStock: 50,
      brand: "Amal Plancher Ciment",
      rating: 0,
      numReviews: 0,
      description:
        "Grade 35 cement suitable for various construction applications. This cement offers high compressive strength and ensures long-lasting durability.",
      type: "ciment-35,ciment-45",
      material: "Limestone",
      reviews: [],
    },
    {
      name: "Ciment 45",
      slug: "ciment-45",
      category: "Ciment",
      image: "/images/cement.jpg",
      price: 400,
      countInStock: 50,
      brand: "Amal Plancher Ciment",
      rating: 0,
      numReviews: 0,
      description:
        "Grade 45 cement suitable for various construction applications. This cement offers high compressive strength and ensures long-lasting durability.",
      type: "ciment-35,ciment-45",
      material: "Limestone",
      reviews: [],
    },
    {
      name: "Poutrelle 10/08",
      slug: "poutrelle-10-08",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 600,
      countInStock: 30,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 10/08 suitable for medium-sized construction projects. Offers a balance of strength and weight for structural support.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Poutrelle 10/10",
      slug: "poutrelle-10-10",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 700,
      countInStock: 25,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 10/10 suitable for heavier construction applications. Provides increased load-bearing capacity and structural stability.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Poutrelle 14/08",
      slug: "poutrelle-14-08",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 800,
      countInStock: 20,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 14/08 designed for larger spans and heavier loads. Ideal for supporting wider structures and distributing weight efficiently.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Poutrelle 14/10",
      slug: "poutrelle-14-10",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 900,
      countInStock: 15,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 14/10 known for its exceptional load-bearing capacity. Ideal for large-scale industrial and commercial construction projects.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Poutrelle 20/10",
      slug: "poutrelle-20-10",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 1200,
      countInStock: 10,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 20/10 designed for extremely heavy loads and long spans. Offers unparalleled structural support and stability.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
  ],
};

export default data;
