import bcrypt from "bcryptjs";

const data = {
  // users: [
  //   {
  //     name: "ismail",
  //     email: "ismail@gmail.com",
  //     password: bcrypt.hashSync("teste"),
  //     isAdmin: true,
  //   },
  //   {
  //     name: "nouha",
  //     email: "nouha@gmail.com",
  //     password: bcrypt.hashSync("123456"),
  //     isAdmin: false,
  //   },
  //   {
  //     name: "kawtar",
  //     email: "kawtar@gmail.com",
  //     password: bcrypt.hashSync("teste123"),
  //     isAdmin: false,
  //   },
  // ],
  employees: [
    {
      fullName: "John Doe",
      image: "/images/employe.jpg",
      cin: "A123456",
      email: "johndoe@example.com",
      phoneNumber: "+1 123-456-7890",
      type: "Full-time",
      salary: 5000,
    },
  ],

  products: [
    {
      name: "Samsung Galaxy S21",
      slug: "samsung-galaxy-s21",
      category: "Smartphone",
      image: "/images/samsung-galaxy-s21.png",
      image1: "/images/samsung-galaxy-s211.png",
      image2: "/images/samsung-galaxy-s212.png",
      image3: "/images/samsung-galaxy-s213.png",
      image4: "/images/samsung-galaxy-s214.png",
      price: 11000,
      countInStock: 8,
      brand: "Samsung",
      rating: 0,
      numReviews: 0,
      description:
        "The Samsung Galaxy S21 is a powerful and feature-rich smartphone. It comes with a stunning display, high-performance processor, and a versatile camera system. Whether you're gaming, streaming, or capturing photos and videos, the Galaxy S21 delivers an exceptional experience.",
      reviews: [],
    },
    //   {
    //     name: "Apple MacBook Pro",
    //     slug: "apple-macbook-pro",
    //     category: "Laptops",
    //     image: "/images/apple-macbook-pro.png",
    //     image1: "/images/apple-macbook-pro1.png",
    //     image2: "/images/apple-macbook-pro2.png",
    //     image3: "/images/apple-macbook-pro3.png",
    //     image4: "/images/apple-macbook-pro4.png",
    //     price: 25000,
    //     countInStock: 5,
    //     brand: "Apple",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Apple MacBook Pro is a powerful and portable laptop. It features a high-resolution Retina display, fast processors, and ample storage. Whether you're a professional designer, developer, or content creator, the MacBook Pro is designed to meet your demanding needs.",
    //   },
    //   {
    //     name: "Sony PlayStation 5",
    //     slug: "sony-playstation-5",
    //     category: "Gaming",
    //     image: "/images/sony-playstation-5.png",
    //     image1: "/images/sony-playstation-51.png",
    //     image2: "/images/sony-playstation-52.png",
    //     image3: "/images/sony-playstation-53.png",
    //     image4: "/images/sony-playstation-54.png",
    //     price: 6000,
    //     countInStock: 3,
    //     brand: "Sony",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Sony PlayStation 5 is the next-generation gaming console. With its powerful hardware and innovative features, the PS5 delivers immersive gaming experiences. Enjoy stunning graphics, fast loading times, and a wide range of games to choose from.",
    //   },
    //   {
    //     name: "LG 4K Smart TV",
    //     slug: "lg-4k-smart-tv",
    //     category: "Electronics",
    //     image: "/images/lg-4k-smart-tv.png",
    //     image1: "/images/lg-4k-smart-tv1.png",
    //     image2: "/images/lg-4k-smart-tv2.png",
    //     image3: "/images/lg-4k-smart-tv3.png",
    //     image4: "/images/lg-4k-smart-tv4.png",
    //     price: 15000,
    //     countInStock: 10,
    //     brand: "LG",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The LG 4K Smart TV offers a stunning visual experience. With its 4K resolution and smart features, you can enjoy your favorite movies, shows, and streaming content with exceptional clarity and convenience. It's the perfect addition to your home entertainment setup.",
    //   },
    //   {
    //     name: "AirPods Pro",
    //     slug: "airpods-pro",
    //     category: "Electronics",
    //     image: "/images/airpods-pro.png",
    //     image1: "/images/airpods-pro1.png",
    //     image2: "/images/airpods-pro2.png",
    //     image3: "/images/airpods-pro3.png",
    //     image4: "/images/airpods-pro4.png",
    //     price: 5000,
    //     countInStock: 10,
    //     brand: "Apple",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The AirPods Pro deliver immersive sound with Active Noise Cancellation. They have a customizable fit and are sweat and water-resistant. With transparency mode, you can hear what's happening around you. The AirPods Pro come with a wireless charging case.",
    //   },
    //   {
    //     name: "Samsung Galaxy A52",
    //     slug: "samsung-galaxy-a52",
    //     category: "Smartphone",
    //     image: "/images/samsung-galaxy-a52.png",
    //     image1: "/images/samsung-galaxy-a521.png",
    //     image2: "/images/samsung-galaxy-a522.png",
    //     image3: "/images/samsung-galaxy-a523.png",
    //     image4: "/images/samsung-galaxy-a524.png",
    //     price: 7000,
    //     countInStock: 5,
    //     brand: "Samsung",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Samsung Galaxy A52 is a versatile and affordable smartphone. It features a vibrant display, powerful performance, and a multi-lens camera system. Whether you're capturing photos, playing games, or staying connected, the Galaxy A52 delivers a great user experience.",
    //   },
    //   {
    //     name: "iPhone 13 Pro",
    //     slug: "iphone-13-pro",
    //     category: "Smartphone",
    //     image: "/images/iphone-13-pro.png",
    //     image1: "/images/iphone-13-pro1.png",
    //     image2: "/images/iphone-13-pro2.png",
    //     image3: "/images/iphone-13-pro3.png",
    //     image4: "/images/iphone-13-pro4.png",
    //     price: 30000,
    //     countInStock: 3,
    //     brand: "Apple",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The iPhone 13 Pro is the flagship smartphone from Apple. It features a stunning Super Retina XDR display, powerful A15 Bionic chip, and advanced camera system. With its premium design and cutting-edge features, the iPhone 13 Pro is the ultimate smartphone for Apple enthusiasts.",
    //   },
    //   {
    //     name: "Dell XPS 13",
    //     slug: "dell-xps-13",
    //     category: "Laptops",
    //     image: "/images/dell-xps-13.png",
    //     image1: "/images/dell-xps-131.png",
    //     image2: "/images/dell-xps-132.png",
    //     image3: "/images/dell-xps-133.png",
    //     image4: "/images/dell-xps-134.png",
    //     price: 20000,
    //     countInStock: 8,
    //     brand: "Dell",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Dell XPS 13 is a compact and powerful laptop. It features a borderless InfinityEdge display, fast processors, and long battery life. Whether you're working, streaming, or multitasking, the XPS 13 offers a seamless and immersive computing experience.",
    //   },
    //   {
    //     name: "HP Spectre x360",
    //     slug: "hp-spectre-x360",
    //     category: "Laptops",
    //     image: "/images/hp-spectre-x360.png",
    //     price: 18000,
    //     countInStock: 10,
    //     brand: "HP",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The HP Spectre x360 is a premium convertible laptop. It combines elegance, versatility, and performance in a sleek design. With its flexible 360-degree hinge, vivid display, and powerful internals, the Spectre x360 is perfect for both work and entertainment.",
    //   },
    //   {
    //     name: "Sony WH-1000XM4 Wireless Noise-Canceling Headphones",
    //     slug: "sony-wh-1000xm4-wireless-noise-canceling-headphones",
    //     category: "Audio",
    //     image: "/images/sony-wh-1000xm4-wireless-noise-canceling-headphones.png",
    //     price: 3000,
    //     countInStock: 5,
    //     brand: "Sony",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Sony WH-1000XM4 Wireless Noise-Canceling Headphones deliver immersive sound and industry-leading noise cancellation. These headphones adapt to your environment and activity, optimizing the sound based on your preferences. With long battery life and comfortable design, they are perfect for music lovers on the go.",
    //   },
    //   {
    //     name: "JBL Flip 5 Waterproof Portable Bluetooth Speaker",
    //     slug: "jbl-flip-5-waterproof-portable-bluetooth-speaker",
    //     category: "Audio",
    //     image: "/images/jbl-flip-5-waterproof-portable-bluetooth-speaker.png",
    //     price: 800,
    //     countInStock: 12,
    //     brand: "JBL",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The JBL Flip 5 is a portable Bluetooth speaker that delivers powerful sound in a compact and waterproof design. With its long-lasting battery and durable construction, you can take this speaker anywhere, whether it's by the pool or on a hiking trip. Connect multiple speakers for a true stereo sound experience.",
    //   },
    //   {
    //     name: "Apple AirPods Max",
    //     slug: "apple-airpods-max",
    //     category: "Audio",
    //     image: "/images/apple-airpods-max.png",
    //     price: 15000,
    //     countInStock: 5,
    //     brand: "Apple",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Apple AirPods Max redefine over-ear headphones with their premium design and exceptional sound quality. These wireless headphones feature high-fidelity audio, adaptive EQ, and active noise cancellation for an immersive listening experience. With their luxurious materials and advanced features, the AirPods Max offer a new level of audio excellence.",
    //   },
    //   {
    //     name: "DJI Mavic 2 Pro",
    //     slug: "dji-mavic-2-pro",
    //     category: "Drones",
    //     image: "/images/dji-mavic-2-pro.png",
    //     price: 20000,
    //     countInStock: 8,
    //     brand: "DJI",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The DJI Mavic 2 Pro is a powerful drone that captures stunning aerial footage. It features a Hasselblad camera with a 1-inch CMOS sensor, offering exceptional image quality. With intelligent flight modes and obstacle sensing, you can capture creative shots with ease.",
    //   },
    //   {
    //     name: "Oculus Quest 2",
    //     slug: "oculus-quest-2",
    //     category: "Virtual Reality",
    //     image: "/images/oculus-quest-2.png",
    //     price: 3000,
    //     countInStock: 7,
    //     brand: "Oculus",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Oculus Quest 2 is a standalone virtual reality headset that provides immersive gaming and entertainment experiences. With its high-resolution display and integrated tracking system, you can explore virtual worlds and engage in multiplayer adventures.",
    //   },
    //   {
    //     name: "Nest Learning Thermostat",
    //     slug: "nest-learning-thermostat",
    //     category: "Smart Home",
    //     image: "/images/nest-learning-thermostat.png",
    //     price: 3000,
    //     countInStock: 5,
    //     brand: "Nest",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Nest Learning Thermostat is a smart home device that learns your heating and cooling preferences and adjusts accordingly. With its intuitive interface and energy-saving features, it helps you maintain a comfortable home environment while reducing energy consumption.",
    //   },
    //   {
    //     name: "Anki Vector Robot",
    //     slug: "anki-vector-robot",
    //     category: "Robots",
    //     image: "/images/anki-vector-robot.png",
    //     price: 4000,
    //     countInStock: 3,
    //     brand: "Anki",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "Anki Vector is a small and intelligent robot that can recognize faces, answer questions, play games, and perform various tasks. With its advanced AI capabilities, it brings personality and interactivity to your home, making it an engaging and fun companion.",
    //   },
    //   {
    //     name: "GoPro HERO9 Black",
    //     slug: "gopro-hero9-black",
    //     category: "Action Cameras",
    //     image: "/images/gopro-hero9-black.png",
    //     price: 5000,
    //     countInStock: 4,
    //     brand: "GoPro",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The GoPro HERO9 Black is a versatile action camera that captures stunning 5K video and high-resolution photos. With its rugged design and advanced stabilization, it's perfect for capturing action-packed moments during outdoor adventures.",
    //   },
    //   {
    //     name: "iRobot Roomba i7+",
    //     slug: "irobot-roomba-i7-plus",
    //     category: "Home Appliances",
    //     image: "/images/irobot-roomba-i7-plus.png",
    //     price: 8000,
    //     countInStock: 6,
    //     brand: "iRobot",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The iRobot Roomba i7+ is an advanced robot vacuum cleaner that offers exceptional cleaning performance. With its smart mapping technology and automatic dirt disposal, it efficiently navigates and cleans your home, freeing up your time for other activities.",
    //   },
    //   {
    //     name: "Nintendo Switch",
    //     slug: "nintendo-switch",
    //     category: "Gaming",
    //     image: "/images/nintendo-switch.png",
    //     price: 6000,
    //     countInStock: 8,
    //     brand: "Nintendo",
    //     rating: 0,
    //     numReviews: 0,
    //     description:
    //       "The Nintendo Switch is a versatile gaming console that allows you to play games on-the-go or connect it to your TV for a traditional console experience. With its innovative design and a wide range of games, it offers a unique and enjoyable gaming experience for all ages.",
    // },
  ],
};

export default data;
