import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "ismail",
      email: "ismail@gmail.com",
      password: bcrypt.hashSync("teste"),
      isAdmin: true,
      isConducteur: false,
    },
    {
      name: "nouha",
      email: "nouha@gmail.com",
      password: bcrypt.hashSync("teste"),
      isAdmin: false,
      isConducteur: false,
    },
  ],
  employees: [
    {
      fullName: "John Doe",
      image: "/images/employe.jpg",
      cin: "A123456",
      email: "johndoe@example.com",
      phoneNumber: "+1 123-456-7890",
      type: "Full-time",
      salary: 5000,
    },
  ],

  products: [
    {
      name: "Agglos A15",
      slug: "agglos-a15",
      category: "Agglos",
      image: "/images/agglos.jpg",
      price: 350,
      countInStock: 75,
      brand: "Amal Agglos",
      rating: 0,
      numReviews: 0,
      description:
        "Agglos A15 is a high-quality concrete block suitable for both residential and commercial construction. It provides strong structural support and longevity.",
      type: "agglos-a15,agglos-a12,agglos-a20",
      material: "Concrete",
      reviews: [],
    },
    {
      name: "Agglos A12",
      slug: "agglos-a12",
      category: "Agglos",
      image: "/images/agglos.jpg",
      price: 300,
      countInStock: 100,
      brand: "Amal Agglos",
      rating: 0,
      numReviews: 0,
      description:
        "Agglos A12 is a versatile concrete block suitable for a wide range of construction projects. It offers excellent load-bearing capacity and durability.",
      type: "agglos-a15,agglos-a12,agglos-a20",
      material: "Concrete",
      reviews: [],
    },
    {
      name: "Agglos A20",
      slug: "agglos-a20",
      category: "Agglos",
      image: "/images/agglos.jpg",
      price: 400,
      countInStock: 50,
      brand: "Amal Agglos",
      rating: 0,
      numReviews: 0,
      description:
        "Agglos A20 is a heavy-duty concrete block designed for demanding construction applications. It delivers superior strength and durability.",
      type: "agglos-a15,agglos-a12,agglos-a20",
      material: "Concrete",
      reviews: [],
    },
    {
      name: "Panneau Treillis Soudé",
      slug: "panneau-treillis-soude",
      category: "Mesh Panels",
      image: "/images/welded-mesh-panel.jpg",
      price: 25,
      countInStock: 200,
      brand: "Amal Mesh",
      rating: 0,
      numReviews: 0,
      description:
        "Panneau Treillis Soudé, also known as Welded Mesh Panel, is ideal for various construction and fencing applications. It offers strength, stability, and versatility for your projects.",
      type: "panneau-treillis-soude",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Hourdis H08",
      slug: "hourdis-h08",
      category: "Hourdis",
      image: "/images/hourdis.jpg",
      price: 10,
      countInStock: 300,
      brand: "Amal Hourdis",
      rating: 0,
      numReviews: 0,
      description:
        "Hourdis H08 is a lightweight concrete block used for flooring systems. It provides efficient insulation and structural support for your construction projects.",
      type: "hourdis-h08,hourdis-h12,hourdis-h15,hourdis-h20",
      material: "Concrete",
      reviews: [],
    },
    {
      name: "Hourdis H12",
      slug: "hourdis-h12",
      category: "Hourdis",
      image: "/images/hourdis.jpg",
      price: 12,
      countInStock: 250,
      brand: "Amal Hourdis",
      rating: 0,
      numReviews: 0,
      description:
        "Hourdis H12 is a medium-weight concrete block suitable for constructing suspended floors. It offers a balance of strength and insulation properties.",
      type: "hourdis-h08,hourdis-h12,hourdis-h15,hourdis-h20",
      material: "Concrete",
      reviews: [],
    },
    {
      name: "Hourdis H15",
      slug: "hourdis-h15",
      category: "Hourdis",
      image: "/images/hourdis.jpg",
      price: 14,
      countInStock: 200,
      brand: "Amal Hourdis",
      rating: 0,
      numReviews: 0,
      description:
        "Hourdis H15 is a heavier concrete block designed for load-bearing applications in construction. It offers superior strength and durability.",
      type: "hourdis-h08,hourdis-h12,hourdis-h15,hourdis-h20",
      material: "Concrete",
      reviews: [],
    },
    {
      name: "Hourdis H20",
      slug: "hourdis-h20",
      category: "Hourdis",
      image: "/images/hourdis.jpg",
      price: 16,
      countInStock: 150,
      brand: "Amal Hourdis",
      rating: 0,
      numReviews: 0,
      description:
        "Hourdis H20 is a heavy-duty concrete block designed for demanding structural applications. It provides exceptional strength and support.",
      type: "hourdis-h08,hourdis-h12,hourdis-h15,hourdis-h20",
      material: "Concrete",
      reviews: [],
    },
    {
      name: "Ciment 35",
      slug: "ciment-35",
      category: "Ciment",
      image: "/images/cement.jpg",
      price: 400,
      countInStock: 50,
      brand: "Amal Plancher Ciment",
      rating: 0,
      numReviews: 0,
      description:
        "Grade 35 cement suitable for various construction applications. This cement offers high compressive strength and ensures long-lasting durability.",
      type: "ciment-35,ciment-45",
      material: "Limestone",
      reviews: [],
    },
    {
      name: "Ciment 45",
      slug: "ciment-45",
      category: "Ciment",
      image: "/images/cement.jpg",
      price: 400,
      countInStock: 50,
      brand: "Amal Plancher Ciment",
      rating: 0,
      numReviews: 0,
      description:
        "Grade 45 cement suitable for various construction applications. This cement offers high compressive strength and ensures long-lasting durability.",
      type: "ciment-35,ciment-45",
      material: "Limestone",
      reviews: [],
    },
    {
      name: "Poutrelle 10/08",
      slug: "poutrelle-10-08",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 600,
      countInStock: 30,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 10/08 suitable for medium-sized construction projects. Offers a balance of strength and weight for structural support.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Poutrelle 10/10",
      slug: "poutrelle-10-10",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 700,
      countInStock: 25,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 10/10 suitable for heavier construction applications. Provides increased load-bearing capacity and structural stability.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Poutrelle 14/08",
      slug: "poutrelle-14-08",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 800,
      countInStock: 20,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 14/08 designed for larger spans and heavier loads. Ideal for supporting wider structures and distributing weight efficiently.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Poutrelle 14/10",
      slug: "poutrelle-14-10",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 900,
      countInStock: 15,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 14/10 known for its exceptional load-bearing capacity. Ideal for large-scale industrial and commercial construction projects.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
    {
      name: "Poutrelle 20/10",
      slug: "poutrelle-20-10",
      category: "Poutrelle",
      image: "/images/poutrelle.jpg",
      price: 1200,
      countInStock: 10,
      brand: "Amal Plancher Poutrelles",
      rating: 0,
      numReviews: 0,
      description:
        "Poutrelle 20/10 designed for extremely heavy loads and long spans. Offers unparalleled structural support and stability.",
      type: "poutrelle-10-08,poutrelle-10-10,poutrelle-14-08,poutrelle-14-10,poutrelle-20-10",
      material: "Steel",
      reviews: [],
    },
  ],
};

export default data;
